### PR TITLE
Resource cloning workaround

### PR DESCRIPTION
**Pull request by chr4**
This is another try to workaround the Chef-13 resource cloning issues. 

This time **removing** some convenience features:
- Automatically creating custom chains when `iptables_ng_rule` provider is used
- Automatically running the `iptables-ng::install` recipe when providers are used

The issue with the file resource in the `rule` provider can't be fixed directly, the previous attemt catching the `ResourceNotFound` exception lead to [issues](https://github.com/chr4-cookbooks/iptables-ng/issues/63). Therefore, this workaround uses a random resource identifier (UNIX timestamp + `rand(1000)`) to work around this.

### CODE REVIEW

**Comment by aalmenar** [comment]
Have you posted a new release to supermarket.chef.io ?

**Comment by chr4** [comment]
No, this branch is to test the changes, will release them afterward the merge to master.

**Comment by aalmenar** [comment]
Have you checked this out ?

https://gist.github.com/danielsdeleo/30a8719901eca6545488

**Comment by chr4** [comment]
Which particular section are you reffering to? I skimmed over it and couldn't find a section related to our problem here. Did I miss something?

**Comment by chr4** [comment]
Released in `v3.0.0`

**Pull request merged**
