### PR TITLE
dev workflow update

### PR DESCRIPTION
**Pull request by nathwill**
- use travis' faster docker-based infrastructure
- test against current ruby bundled with Chef
- `site :opscode` is deprecated in modern berks, update to use supermarket universe endpoint
- add rakefile for common development tasks
- add missing chefspec matchers
- use latest bento boxes

### CODE REVIEW

**Comment by chr4** [comment]
This looks good. Can you migrate to the ruby-1.9 hash syntax, and fix other rubocop errors (guess %w() doesn't allow additional whitespaces?) Will merge then.

**Comment by nathwill** [comment]
@chr4 ok, i updated the cops that i was able to find on here using the linters included in the latest chefdk (via `chef exec rake`), or that travis turned up. i didn't see anything about whitespace around %w(), so i guessed at which ones you saw (rakefile?). lmk if there's others.

**Comment by chr4** [comment]
Yeah I meant the two you fixed in 35ea05f. I thought that rubocop complains about those, not sure if it still does.
Thanks! Merging.

**Comment by chr4** [comment]
Out of interest: What's the advantage using rake as a wrapper around foodcritic/ rubocop?

**Comment by nathwill** [comment]
just convenient to have one command to run all of the linting/unit testing, and making it easier to remember how to check all of them (`chef exec rake` vs `chef exec rubocop` + `chef exec foodcritic -f any .` + `chef exec rspec`.

**Pull request merged**
