### PR TITLE
Fix issue with fatal error updating the chain file content

### PR DESCRIPTION
**Pull request by andytson**
Resources don't have property methods, but have single methods that set/get the value

### CODE REVIEW

**Comment by chr4** [comment]
Thanks for spotting the issue and the pull-request!

I've encountered this error on a system with an ancient `chef-client`, but assumed this was a compatibility issue. Which version of `chef-client` are you encountering the issue with?
Does the change affect recent `chef-client` versions?

**Comment by andytson-inviqa** [comment]
This was chef 12.10.4

**Comment by andytson-inviqa** [comment]
Sorry, I've tracked it back to the source chef version that added the property method way, and see https://github.com/chef/chef/commit/c7f314f08d8baa0d5d8743153e244f0b4daec5e3
so 12.5. The person who I was reporting it for probably reported the wrong server's chef version

**Comment by chr4** [comment]
If removing the `=` adds compatibility for older `chef-clients` for free, while not hurting newer clients, I think merging this would be worth it.

**Comment by chr4** [comment]
476871e1 was introducing this @sspans, can you comment on this?

**Comment by chr4** [comment]
After checking the chef-client source, this seems like a no brainer. Merging.

**Comment by chr4** [comment]
Released in `v2.3.1`. Thanks again!

**Comment by sspans** [comment]
@andytson-inviqa thanks for catching that one!

**Pull request merged**
